# Generated by Django 4.1.7 on 2023-03-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='user.png', null=True, upload_to=''),
        ),
    ]
